### ISSUE TITLE
Time rail not visible in WordPress 4.1

### ISSUE THREAD

**Issue by jayj** [justintadlock/theme-mediaelement#6]
In WordPress 4.1, the time rail is not visible.

![Image before](http://i.imgur.com/PWlWFyt.png)

To fix it I added this CSS:

```
.mejs-time-rail {
    position: relative; /* fixes wrong .mejs-float position */
}

.mejs-time-rail .mejs-time-total {
    height: 10px;
}

.mejs-time-rail .mejs-time-slider {
    display: block;
}
```

![Image after](http://i.imgur.com/zel33uT.png)

However, there's still some issues after the new CSS. The buffering is a bit too wide:

![Image of buffering](http://i.imgur.com/98ixtQe.png)

**Comment by jayj** [comment]
There's also an issue with audio playlists (I don't know about single embeds, will test later)

The time rail is showing for like half a second before it disappears. Here's a gif:

![gif of issue](http://i.imgur.com/k1T29iU.gif)

**Comment by justintadlock** [comment]
Thanks for this. There's definitely some things I need to improve for 4.1.  Feel free to add pull requests for the `dev` branch too.

**Comment by jayj** [comment]
Issue number two with the audio only happens when there's more than one playlist on a page and the playlist is _not_ the first one. So it might be something in Mediaelement's width calculations.

Core has similar issues: https://core.trac.wordpress.org/ticket/30281#comment:18

**Comment by jayj** [comment]
Core just added this CSS:
https://core.trac.wordpress.org/changeset/30907/trunk

Will take a look at creating a PR later this week if you or others don't do it first.

**Comment by jayj** [comment]
This fixed the audio issue:

```
.mejs-controls a.mejs-horizontal-volume-slider { 
     display: table; 
} 
```

**Comment by justintadlock** [comment]
Fixed in above commit.
